version: '3.7'

services:
  bd:
    image: mariadb:latest
    container_name: bd
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    restart: always
  app:
    build: "./"
    container_name: app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - bd
